version: "3.6"
services:
  nginx_egress:
    image: nginx:1.21-alpine
    container_name: egress
    links:
      - nginxmef:nginxmef
    volumes:
      - ./default_egress.nginx:/etc/nginx/conf.d/default.conf
      - ./certslocalhost:/etc/nginx/certs
    ports:
      - "80:80"
    depends_on:
      - nginxmef
      - mef
    networks:
      main:
        aliases:
          - egress
  nginxmef:
    image: nginx:1.21-alpine
    container_name: mef_front
    links:
      - mef:mef
    ports:
      - "7070:7070"
    volumes:
      - ./default_mef.nginx:/etc/nginx/conf.d/default.conf
      - ./certslocalhost:/etc/nginx/certs
    networks:
      main:
        aliases:
          - nginxmef
  mef:
    image: golang:1.17-alpine
    container_name: mef
    working_dir: /app
    command: go run main.go
    volumes:
      - .:/app
    networks:
      main:
        aliases:
          - mef
networks:
  main: